version: "3.8"
services:
  sb-website:
    build:
      context: ./sneakbike
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command: "npm run serve"

  sb-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: "uvicorn main:app --host 0.0.0.0"
